# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExerciseBlockchain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExerciseBlockchain

    pod 'Alamofire'
    pod 'SwiftCharts'
    pod 'HandyJSON'

  target 'ExerciseBlockchainTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExerciseBlockchainUITests' do
    # Pods for testing
  end

end
